testing and fixing outdated atlas generation scripts
brainglobe/brainglobe-atlasapi pull request #249
Opened 2024-02-27 14:42 UTC by viktorpm

## Description

We would like to test if the atlas validation functions pass after regenerating atlases (see: #201).
At the moment, the atlas generation scripts are outdated, so to regenerate the atlases, first, we need to fix and tidy the scripts.  

**What is this PR**

- [x] Bug fix
- [x] Addition of a new feature
- [ ] Other

**Why is this PR needed?**

We need an up-to-date version of the atlas generation scripts and the atlases

**What does this PR do?**

Fixes syntax errors, removes outdated packages

## References

#201

## How has this PR been tested?

It's just a draft pr so far

## Is this a breaking change?

It might due to changes in `vedo` syntax and functions

## Does this PR require an update to the documentation?

Yes

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [ ] The code has been formatted with [pre-commit](https://pre-commit.com/)

2024-02-27 16:00 UTC, viktorpm commented
**Script errors:**

| Script                        | Error                                    | Note |
|-------------------------------|------------------------------------------|------|
| admba_3d_dev_mouse.py        | na                                       | na   |
| allen_cord.py                 | BadZipFile: File is not a zip file       | na   |
| allen_mouse.py                | no error                                 | na   |
| azba_zfish.py                 | AttributeError: 'Mesh' object has no attribute 'smoothLaplacian' | na   |
| example_mouse.py              | na                                       | na   |
| humanatlas.py                 | na                                       | na   |
| kim_developmental_ccf_mouse.py| na                                       | na   |
| kim_mouse.py                  | na                                       | na   |
| mpin_zfish.py                 | na                                       | na   |
| osten_mouse.py                | na                                       | na   |
| perens_lsfm_mouse.py          | na                                       | na   |
| princeton_mouse.py            | na                                       | na   |
| whs_sd_rat.py                 | na                                       | na   |

2024-02-27 18:00 UTC, viktorpm commented
**Steps to test changes on the HPC:**

```
module load mamba
mamba init
mamba create -n bg-atlasapi python=3.11
mamba activate bg-atlasapi
git clone https://github.com/brainglobe/brainglobe-atlasapi.git
cd brainglobe-atlasapi/
git checkout fixing_atlas_scripts
pip install -e ".[allenmouse, dev]"
pip install scikit-image
pip install imio
pip install brainio
cd brainglobe_atlasapi/atlas_generation/atlas_scripts
```

2024-02-29 16:34 UTC, alessandrofelder requested changes
Looking good - think we just need to fix the dependencies in `pyproject.toml` and then this is good to go 🚀

2024-02-29 16:34 UTC, alessandrofelder commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/admba_3d_dev_mouse.py
> +######## I had to manually install this
This should be added to the `dependencies` in `pyproject.toml` then, I think,

2024-02-29 16:34 UTC, alessandrofelder commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/humanatlas.py
> +### I had to install manually
Again, worth adding to the dependencies. If it is very big or hard-to-install, it can be an optional dependency like `allensdk`.

2024-02-29 16:34 UTC, alessandrofelder commented on brainglobe_atlasapi/atlas_generation/volume_utils.py
> +######## I had to manually install this
We should depend on `brainglobe-utils.imageio` instead (see https://github.com/brainglobe/brainglobe-utils/pull/33 for details), which may need to be added to the dependencies.

2024-03-01 16:52 UTC, alessandrofelder approved these changes

2024-03-01 16:52 UTC, merged