Removed empty code box at the end. (Should it contain code to return side name instead of number, as written in the text above it?)
brainglobe/brainglobe-atlasapi pull request #335
Opened 2024-07-31 21:59 UTC by kjungwoo5

2024-08-01 09:21 UTC, adamltyson requested changes
Thanks @kjungwoo5, I didn't realise we had so many typos!

I've made a few suggestions. Most of these aren't actually corrections to your changes, but other things I noticed while reviewing this. Let me know what you think. 

You can just accept them via the pull request if you like.

2024-08-01 09:21 UTC, adamltyson commented on tutorials/Atlas API usage.ipynb
> +                "the levels of the hierarchy depend on the underlying atlas, so we cannot ensure the goodness and consistency of their hierarchy tree.\n",
```suggestion
                "The levels of the hierarchy depend on the underlying atlas, so we cannot ensure the goodness and consistency of their hierarchy tree.\n",
```

2024-08-02 11:22 UTC, adamltyson commented
Thanks @kjungwoo5. I think there's just one suggestion outstanding, then we're ready to go!

2024-08-02 13:03 UTC, kjungwoo5 commented on tutorials/Atlas API usage.ipynb
> +                "### 1.1 Anatomical, annotations and hemispheres stack"
I'll make changes in the subheadings below to reflect this change, then commit everything at once.

2024-08-02 13:38 UTC, alessandrofelder approved these changes

2024-08-02 13:43 UTC, merged