added nadkarni_mri_mouselemur
brainglobe/brainglobe-atlasapi pull request #411
Opened 2024-09-12 16:53 UTC by PolarBean

Here this addresses this issue. Adding a mouse lemur atlas into brainglobe.
https://github.com/brainglobe/brainglobe-atlasapi/issues/410
This will be ready once I double check the orientation.

2024-09-23 15:41 UTC, alessandrofelder requested changes
Thanks, @PolarBean 

Largely looks good to me - made some comments to increase the code quality (I hope!)

I've run the validation on the atlas locally, and it looks like there's some spurious pixels in the annotation here:

![image](https://github.com/user-attachments/assets/9abedff0-22bb-4f07-8568-77454d1000b7)

Not sure whether we should ask the original authors to fix this, or fix it ourselves programmatically. Thoughts welcome!

2025-01-23 05:19 UTC, PolarBean commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/nadkarni_mri_mouselemur.py
> +    return new_df.to_dict("records")
Not the output segmentation but the output metadata yeah :)

2025-01-23 05:39 UTC, PolarBean commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/nadkarni_mri_mouselemur.py
> +    tree = get_structures_tree(structures)
agreed

2025-01-23 05:40 UTC, PolarBean commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/nadkarni_mri_mouselemur.py
> +import mp
I removed it

2025-01-23 05:40 UTC, PolarBean commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/nadkarni_mri_mouselemur.py
> +# hierarchical
removed

2025-01-23 05:46 UTC, PolarBean commented
This should be ready for rereview

2025-01-23 05:47 UTC, PolarBean commented
> Thanks, @PolarBean
> 
> Largely looks good to me - made some comments to increase the code quality (I hope!)
> 
> I've run the validation on the atlas locally, and it looks like there's some spurious pixels in the annotation here (see left of canvas in screenshot below):
> 
> ![image](https://private-user-images.githubusercontent.com/10500965/369948965-9abedff0-22bb-4f07-8568-77454d1000b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2MTEyNTksIm5iZiI6MTczNzYxMDk1OSwicGF0aCI6Ii8xMDUwMDk2NS8zNjk5NDg5NjUtOWFiZWRmZjAtMjJiYi00ZjA3LTg1NjgtNzc0NTRkMTAwMGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIzVDA1NDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYjIyNTYwZDE4ZDk1NTlmZGVjMjM5ZTJiNmM4MGRiMTI2NjU0MTZiNDdmYjRjMTQyZGQwM2NkNmE4YjYyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9f_5x-EV1AAjCRqE7zyAt5oER0Di2O7X6SfiJxBeAXg)
> 
> Not sure whether we should ask the original authors to fix this, or fix it ourselves programmatically. Thoughts welcome!

related to other discussiongs I think we merge for the moment and make a brainglobe version later on with these pixels removed.

2025-01-27 16:57 UTC, alessandrofelder approved these changes
Looks good to me.
Tiny bug in the orientation, I think - I've suggested a change.

2025-01-27 16:57 UTC, alessandrofelder commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/nadkarni_mri_mouselemur.py
> +ORIENTATION = "ria"
I think this should be `lia` (because if I run it with that the "Thalamus R" region is in the right hemisphere in `brainrender-napari` (It's in the left hemisphere otherwise).

![image](https://github.com/user-attachments/assets/ee350736-2515-4df2-980d-6ce046e1ac11)

2025-01-27 21:53 UTC, PolarBean commented on brainglobe_atlasapi/atlas_generation/atlas_scripts/nadkarni_mri_mouselemur.py
> +ORIENTATION = "ria"
Great catch

2025-01-28 14:58 UTC, alessandrofelder commented
Awesome - thanks again @PolarBean 
I've uploaded to GIN and will have a go at adding it to various docs tables now.

2025-01-28 14:58 UTC, merged